language: node_js
before_script:
  - npm install -g gatsby-cli
node_js:
  - "8"
  - "10"
after_success:
  - yarn run semantic-release
deploy:
  provider: script
  script: cd docs/ && yarn install && yarn run deploy
  skip_cleanup: true
  on:
    branch: master
